feat/circular-radio-button
atlasgroupcz/react-atlantic pull request #238
Opened 2021-06-10 11:52 UTC by nikolsrnickova

2021-06-10 12:02 UTC, topolanekmartin requested changes

2021-06-10 12:02 UTC, topolanekmartin commented on src/components/Radio/views/Circular/styles/Circular.style.ts
> +    flex-shrink: 0;
Tady to není potřeba ne? :)

2021-06-10 12:02 UTC, topolanekmartin commented on src/components/Radio/views/Circular/styles/Circular.style.ts
> +    gap: ${({ theme }) => theme.padding.sm};
Prosím nahradit

2021-06-11 07:38 UTC, filipkastovsky approved these changes

2021-06-11 07:40 UTC, merged