Refactor/input
atlasgroupcz/react-atlantic pull request #38
Opened 2020-08-28 13:18 UTC by pro0255

2020-08-30 20:14 UTC, filipkastovsky requested changes

2020-08-30 20:14 UTC, filipkastovsky commented on src/components/Input/view/base/style/size.ts
> +            return sizeSmall();
Není to nějaké domotané? :D

2020-08-30 20:14 UTC, filipkastovsky commented on src/components/Input/view/base/style/size.ts
> +`;
To by mohly být jenom konstanty, je to takto kvůli konzistence?

2020-08-31 12:33 UTC, topolanekmartin commented on src/components/Input/view/base/style/parts/size/size.ts
> +        width: ${sizeObj[tranformedSize]}px;
Budeme potřebovat pro každou velikost jinou šířku inputu? Nechal bych jednu velikost, která se bude vždy měnit z 90% případů dle konkrétní implementace.

2020-08-31 12:34 UTC, topolanekmartin commented on src/components/Input/view/base/style/parts/sizeDiff/sizeDiff.ts
> +export const sizeDiffInput: SizeDiffInput = (size, theme) => {
Nejsem si jistý, co znamená DiffInput..?

2020-08-31 12:35 UTC, topolanekmartin commented on src/components/Input/view/base/style/parts/sizeDiff/sizeDiff.ts
> +    span + i {
Zapsal bych spíš referencí na konkrétní styled komponentu

2020-08-31 12:49 UTC, filipkastovsky commented on src/components/Input/view/base/style/parts/fillWidth/fullWidth.ts
> +        : css``;
Určitě ne, && operátor vrací levou stranu pokud je falsy, když už, tak `""`, ale to není kritické

2020-08-31 13:03 UTC, topolanekmartin commented on src/components/Input/view/base/style/parts/fillWidth/fullWidth.ts
> +        : css``;
Tomu nerozumím. Pokud by `value` bylo `false` tak se podmínka přece neprovede. Tzn. ve výsledku se vrátí:

```
css``
```
Na tom něco špatného je?

2020-09-10 12:19 UTC, merged